---
- hosts: my_workstation
  tasks:
    - name: Import role localhosts
      import_role:
        name: localhosts
      tags:
        - workstation
    - name: Import role xorg
      import_role:
        name: xorg
      tags:
        - workstation
    - name: Import role game
      import_role:
        name: game
      tags:
        - never
        - game

- hosts: vhorst
  tasks:
    - name: Import role vhorst
      import_role:
        name: vhorst
      tags:
        - infra
        - horst