- name: install AppImages
  block:
    - name: install dependencies
      become: true
      package:
        name:
          - fuse2
      when: ansible_distribution in [ 'Ubuntu' ]
    - name: prepare AppImage folder
      become: true
      become_user: "{{ user }}"
      file:
        path: "/home/{{ user }}/Applications"
        state: directory
    - become_user: "{{ user }}"
      become: true
      block:
        - include_tasks: install-joplin.yml