- name: Install abcde (ubuntu)
  when: ansible_distribution in ['Ubuntu']
  become: yes
  package:
    name: abcde
    state: present


- name: install abcde dependencies (arch)
  when: ansible_distribution in ['Arch','Archlinux']
  become: true
  package:
    name:
      - id3v2
- name: Install abcde from AUR (arch)
  when: ansible_distribution in ['Arch','Archlinux']
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: abcde
    use: paru
    state: present

- name: link abcde config
  become: yes
  become_user: "{{ user }}"
  file:
    src: "/home/{{ user }}/dotfiles/home/.abcde.conf"
    dest: "/home/{{ user }}/.abcde.conf"
    state: link
