
- name: install ignite-cli
  when: ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]
  shell:
    cmd: |
      curl https://get.ignite.com/cli | bash
      sudo mv ignite /usr/local/bin/
    executable: /bin/bash
  args:
    chdir: "{{ userhome }}"
    creates: "/usr/local/bin/ignite"
  tags: [ 'never','ignite' ]