- name: install borgbackup (arch)
  when: ansible_distribution in ['Arch','Archlinux']
  become: true
  vars:
    distro_packages:
      'Arch':
        ssh_server: "openssh"
      'Archlinux':
        ssh_server: "openssh"
      'Ubuntu':
        ssh_server: "openssh-server"
  package:
    name:
      - borg
      - python-llfuse
      - "{{ distro_packages[ansible_distribution]['ssh_server'] | default ('') }}"
      - borgmatic

- name: Install borgtui-git from AUR (arch)
  tags: ['aur']
  include_tasks: with-paru-install-borgtui.yml
  when: ansible_distribution in ['Arch', 'Archlinux']