- vars:
    venv_path: "/home/{{ package_user }}/.local/venv/{{ package_env_name }}"
  block:
    - name: Define Python interpreter and packages based on distribution
      set_fact:
        python_packages:
          Ubuntu:
            interpreter: python3
            packages: ['python3', 'python3-pip', 'python3-venv']
          Archlinux:
            interpreter: python
            packages: ['python', 'python-pip', 'python-virtualenv']

    - name: Install Python and pip
      become: true
      package:
        name: "{{ python_packages[ansible_distribution]['packages'] }}"
        state: present
      when: ansible_distribution in python_packages

    - name: Create virtual environment
      become: true
      become_user: "{{ package_user }}"
      command: "{{ python_packages[ansible_distribution]['interpreter'] }} -m venv {{ venv_path }}"
      args:
        creates: "{{ venv_path }}"

    - name: "Install {{ package_name }}"
      become: true
      become_user: "{{ package_user }}"
      pip:
        name: "{{ package_name }}"
        executable: "{{ venv_path }}/bin/pip"
        state: present
    - name: "Add {{ package_name }} bin"
      become: true
      lineinfile:
        path: "/home/{{ package_user }}/.profile"
        line: "{{ item.line }}"
        create: true
        owner: "{{ package_user }}"
        group: "{{ package_user }}"
      loop:
        - { line: "### {{ package_name }} ###" }
        - { line: "export PATH=$PATH:{{ venv_path }}/bin" }