- name: install AppImages
  block:
    - name: prepare AppImage folder
      become: true
      become_user: "{{ user }}"
      file:
        path: "/home/{{ user }}/Applications"
        state: directory
    - become_user: "{{ user }}"
      become: true
      block:
        - import_tasks: install-joplin.yml
        - import_tasks: install-jetbrains.yml
