- name: install joplin
  become: yes
  become_user: "{{ user }}"
  block:
    - shell: |
        USER_HOME="/home/{{ user }}"
        YAML_URL="https://github.com/laurent22/joplin/releases/latest/download/latest-linux.yml"
        YAML_DEST="$USER_HOME/joplin-latest-linux.yml"
        APP_DIR="$USER_HOME/Applications"
        curl -L -o $YAML_DEST $YAML_URL
        JOPLIN_PATH=$(yq eval -o=json $YAML_DEST | jq -r '.path')
        JOPLIN_FILE_URL=$(yq eval -o=json $YAML_DEST | jq -r '.files[0].url')
        curl -L -o $APP_DIR/$JOPLIN_PATH "https://github.com/laurent22/joplin/releases/latest/download/$JOPLIN_FILE_URL"
        chmod 0500 $APP_DIR/$JOPLIN_PATH
      args:
        executable: /bin/bash
