- name: install neowim (arch)
  when: ansible_distribution in [  'Arch', 'Archlinux' ]
  become: yes
  package:
    name:
      - neovim
      - ripgrep
      - fzf
      - fd
- name: install neowim (ubuntu)
  when: ansible_distribution in [ 'Ubuntu' ]
  become: yes
  block:
    - name: install neovim
      shell:
        cmd: |
          sudo rm -rf /opt/nvim-linux-x86_64
          sudo rm /usr/bin/nvim-linux-x86_64
          curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz && \
          sudo tar -C /opt -xzf nvim-linux-x86_64.tar.gz
          sudo ln -s /opt/nvim-linux-x86_64/bin/nvim /usr/bin/nvim
        executable: /bin/bash
        creates: /usr/bin/nvim
    - name: install telescope dependencies
      package:
        name:
          - fzf
          - fd-find
          - ripgrep

- name: create ~/.config/nvim
  become: true
  become_user: "{{ user }}"
  file:
    path: "{{ userhome }}/.config/nvim"
    state: directory
- name: link neovim init.lua
  become: true
  become_user: "{{ user }}"
  file:
    src: "{{ dot_files }}/home/.config/nvim/init.lua"
    dest: "{{ userhome }}/.config/nvim/init.lua"
    state: link
- name: link neovim lua/
  become: true
  become_user: "{{ user }}"
  file:
    src: "{{ dot_files }}/home/.config/nvim/lua"
    dest: "{{ userhome }}/.config/nvim/lua"
    state: link
- name: link neovim after/
  become: true
  become_user: "{{ user }}"
  file:
    src: "{{ dot_files }}/home/.config/nvim/after"
    dest: "{{ userhome }}/.config/nvim/after"
    state: link
- name: link nvchad
  become: true
  become_user: "{{ user }}"
  file:
    src: "{{ dot_files }}/home/.config/nvchad"
    dest: "{{ userhome }}/.config/nvchad"
    state: link
- name: link lazyvim
  become: true
  become_user: "{{ user }}"
  file:
    src: "{{ dot_files }}/home/.config/lazyvim"
    dest: "{{ userhome }}/.config/lazyvim"
    state: link
