- name: install golang
  become: yes
  block:
    - name: install golang (get_url)
      become_user: "{{  go_user }}"
      become: yes
      get_url:
        url: https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz
        checksum: "sha256:{{ golang_sha256 }}"
        mode: 0755
        dest: "/home/{{ go_user }}/golang-{{ golang_version }}.tar.gz"
      register: golangversion
    - name: install golang (remove old version)
      file:
        path: /usr/local/go
        state: absent
      when: golangversion.changed
    - name: install golang
      shell:
        chdir: "/home/{{ user }}"
        cmd: |
          tar -xf golang-{{ golang_version }}.tar.gz -C /usr/local
      when: golangversion.changed
    - name: install golang (add to path)
      lineinfile:
        path: "/etc/profile"
        line: "{{ item.line }}"
      loop:
      - { line: "### go-lang ###" }
      - { line: "export PATH=$PATH:/usr/local/go/bin" }
      when: golang_version is defined

- name: init golang
  become: yes
  become_user: "{{ user }}"
  vars:
    golib_path: "/home/{{ user }}/git/go-lib/.ignore"
  block:
    - name: init golang (mkdir go-lib)
      file:
        path: "{{ golib_path | dirname }}"
        state: directory
    - name: init golang (create go-lib)
      file:
        path: "{{ golib_path }}"
        state: touch
      changed_when: false
    - name: init golang (update .profile)
      lineinfile:
        path: "/home/{{ user }}/.profile"
        line: "{{ item.line }}"
        create: true
      loop:
        - { line: "### go-lang ###" }
        - { line: "export GOPATH=~/git/go-lib" }
        - { line: "export GOROOT=/usr/local/go" }
        - { line: "export PATH=$PATH:$GOROOT/bin:$GOPATH/bin" }
        - { line: "export GOPRIVATE=\"dev.azure.com\"" }