- when: ansible_distribution in ['Arch', 'Archlinux','Ubuntu']
  become_user: "{{ rust_user }}"
  become: yes
  block:
  - name: Check if .cargo directory exists in home directory
    stat:
      path: "/home/{{ rust_user }}/.cargo"
    register: rustup_directory
  - name: Download and install Rustup if .rustup directory doesn't exist
    get_url:
      url: "https://sh.rustup.rs"
      dest: "/tmp/rustup-init.sh"
      mode: '0755'
    when: not rustup_directory.stat.exists
  - name: Run Rustup initialization script
    command: "/tmp/rustup-init.sh -y"
    args:
      creates: "/home/{{ rust_user }}/.cargo/bin/cargo"  # Ensures idempotence
    when: not rustup_directory.stat.exists

  - name: Set Rust environment variables for bash
    lineinfile:
      dest: "/home/{{ rust_user }}/.bashrc"
      line: "source $HOME/.cargo/env"
      create: yes
    when: not rustup_directory.stat.exists

  - name: Set Rust environment variables for zsh
    lineinfile:
      dest: "/home/{{ rust_user }}/.zshrc"
      line: "source $HOME/.cargo/env"
      create: yes


  - name: Set default Rust version and update
    shell: |
      export PATH="/home/{{ rust_user }}/.cargo/bin:$PATH"
      rustup default stable && rustup update
