- name: install appimagelauncher (Ubuntu)
  become: yes
  block:
    - name: Add appimagelauncher ppa
      apt_repository:
        repo: ppa:appimagelauncher-team/stable
        state: present
    - name: apt update
      apt:
        update_cache: true
      changed_when: false
    - name: install appimagelauncher
      package:
        name: appimagelauncher
  when: ansible_distribution == 'Ubuntu'

- name: install appimagelauncher using kewlfft.aur collection (Arch)
  tags: [ 'always', 'aur']
  include_tasks: with-paru-install-app-image-launcher.yml
  when: ansible_distribution in [ 'Arch', 'Archlinux' ]

- name: link appimagelauncher.cfg
  become: true
  become_user: "{{ user }}"
  file:
    src: "{{ dot_files }}/home/.config/appimagelauncher.cfg"
    dest: "{{ userhome }}/.config/appimagelauncher.cfg"
    state: link
