- name: install jetbrains toolbox
  become: true
  become_user: "{{ user }}"
  vars:
    tar_file: "{{ userhome }}/jetbrains-toolbox-{{ jetbrains_toolbox_version }}.tar.gz"
  block:
    - name: install req (Arch)
      when: ansible_distribution in [ 'Arch', 'Archlinux' ]
      become: true
      package:
        name:
          - fuse2 
          - libxi 
          - libxrender
          - libxtst
          - fontconfig 
          - gtk3 
          - tar
    - name: install req (Ubuntu)
      when: ansible_distribution in [ 'Ubuntu' ]
      become: true
      package:
        name:
          - libfuse2
          - fuse
          - fontconfig
          - tar
    - name: download toolbox
      get_url:
        url: "https://download.jetbrains.com/toolbox/jetbrains-toolbox-{{ jetbrains_toolbox_version }}.tar.gz"
        dest: "{{ tar_file }}"
    - name: untar and move app image
      shell:
        chdir: "{{ userhome }}/"
        cmd: |
          mkdir -p {{ userhome }}/Applications
          chmod u+w {{ userhome }}/Applications
          tar -xf {{ tar_file }} -C {{ userhome }}/Applications
          rm {{ tar_file }}
          mv {{ userhome }}/Applications/jetbrains-toolbox-{{ jetbrains_toolbox_version}}/jetbrains-toolbox {{ userhome }}/Applications/Jetbrains-toolbox-{{ jetbrains_toolbox_version }}
          rmdir {{ userhome }}/Applications/jetbrains-toolbox-{{ jetbrains_toolbox_version}}
        creates: "Jetbrains-toolbox-{{ jetbrains_toolbox_version }}"
