- name: install abcde dependencies
  when: ansible_distribution in ['Arch','Archlinux','Ubuntu']
  become: true
  package:
    name:
      - id3v2

- name: Install abcde (ubuntu)
  when: ansible_distribution in ['Ubuntu']
  become: yes
  package:
    name: abcde
    state: present



- name: Install abcde from AUR (arch)
  tags: ['aur']
  include_tasks: with-paru-install-abcde.yml
  when: ansible_distribution in ['Arch', 'Archlinux']

- name: link abcde config
  become: yes
  become_user: "{{ user }}"
  file:
    src: "/home/{{ user }}/dotfiles/home/.abcde.conf"
    dest: "/home/{{ user }}/.abcde.conf"
    state: link
