- name: Add ppa (Ubuntu)
  block:
  - name: Add strawberry ppa
    apt_repository:
      repo: ppa:jonaski/strawberry
      state: present
  - name: apt update
    apt:
      update_cache: true
    changed_when: false
  when: ansible_distribution == 'Ubuntu'

- name: install strawberry 
  become: true
  package:
    name: 
      - "strawberry"

