- name: Install Oh-My-Zsh
  become: yes
  become_user: "{{ user }}"
  when: ansible_distribution in ['Arch', 'Archlinux','Ubuntu']
  block:
    - name: Check if .oh-my-zsh directory exists in home directory
      stat:
        path: "{{ userhome }}/.oh-my-zsh"
      register: oh_my_zsh
    - name: Install Oh-My-Zsh
      shell:
        cmd: |
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
          git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
      when: not oh_my_zsh.stat.exists or oh_my_zsh.stat.isdir is not sameas true
    - name: Set Oh-My-Zsh theme
      shell: "/usr/bin/zsh -c 'source {{ userhome }}/.oh-my-zsh/oh-my-zsh.sh; omz theme set powerlevel10k/powerlevel10k'"
      when: not oh_my_zsh.stat.exists or oh_stat.isdir is not sameas true
    - name: link .p10k.zsh
      when: ansible_distribution in ['Arch', 'Archlinux', 'Ubuntu']
      file:
        src: "{{ dot_files }}/home/.p10k.zsh"
        dest: "{{ userhome }}/.p10k.zsh"
        state: link