- name: install appimagelauncher (Ubuntu)
  block:
    - name: Add keepass ppa
      apt_repository:
        repo: ppa:appimagelauncher-team/stable
        state: present
    - name: apt update
      apt:
        update_cache: true
      changed_when: false
    - name: install appimagelauncher
      become: true
      package:
        name: appimagelauncher
  when: ansible_distribution == 'Ubuntu'

- name: install appimagelauncher using kewlfft.aur collection (Arch)
  become: yes
  become_user: app_builder
  environment:
    EDITOR: "true"
  kewlfft.aur.aur:
    name: "appimagelauncher"
    use: "paru"
  when: ansible_distribution in ['Arch', 'Archlinux']

- name: link appimagelauncher.cfg
  become: true
  become_user: "{{ user }}"
  file:
    src: "{{ dot_files }}/home/.config/appimagelauncher.cfg"
    dest: "{{ userhome }}/.config/appimagelauncher.cfg"
    state: link
