- name: Add ppa (Ubuntu)
  when: ansible_distribution in [ 'Ubuntu' ]
  become: yes
  block:
  - name: Add keepass ppa
    apt_repository:
      repo: ppa:phoerious/keepassxc
      state: present
  - name: apt update
    apt:
      update_cache: true
    changed_when: false

- name: install keepassxc
  when: ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]
  become: yes
  package:
    name: 
      - keepassxc


