- name: install joplin
  become: yes
  become_user: "{{ user }}"
  block:
    - shell: |
        BOOTSTRAP_HASKELL_NONINTERACTIVE=1 curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh