- name: install common packages
  become: true
  vars:
    distro_packages:
      'Arch':
        wallpaper: 'archlinux-wallpaper'
        dust: 'dust'
      'Archlinux':
        wake_on_lan: 'wol'
        base_devel: 'base-devel'
        btop: 'btop'
        dust: 'dust'
      'Ubuntu':
        wake_on_lan: 'wakeonlan'
        base_devel: 'build-essential'
#        fixme falling back to htop
        btop: 'htop'
        dust: 'du-dust'
  package:
    name:
      - curl
      - feh
      - jq
      - "{{ distro_packages[ansible_distribution]['btop'] | default ('') }}"
      - "{{ distro_packages[ansible_distribution]['base_devel'] | default ('') }}"
      - yt-dlp
      - nnn
      - zsh
      - fzf
      - rsync
      - "{{ distro_packages[ansible_distribution]['wake_on_lan'] | default ('') }}"
      - tmux
      - "{{ distro_packages[ansible_distribution]['dust'] | default ('') }}"

- name: add /usr/local/bin to path
  become: true
  lineinfile:
    path: "/etc/profile"
    line: "export PATH=$PATH:/usr/local/bin"


