- name: Add helix ppa (Ubuntu)
  when: ansible_distribution in [ 'Ubuntu' ]
  become: yes
  block:
    - name: Add helix ppa
      apt_repository:
        repo: ppa:maveonair/helix-editor
        state: present
    - name: apt update
      apt:
        update_cache: true
      changed_when: false

- name: install helix
  when: ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]
  become: yes
  package:
    name:
      - helix


