- vars:
    user: "{{ lookup('env','USER_NM') }}"
    new_ansible_user: "{{ lookup('env','TOOR_NM') }}"
    dot_files: "/home/{{ user }}/dotfiles"
    userhome: "/home/{{ user }}"
  block:
  - name: install common packages
    import_tasks: install-common-packages.yml

  - name: update user
    import_tasks: update-user.yml

  - name: install git
    import_tasks: install-git.yml

  - name: install appimagelauncher
    import_tasks: install-app-image-launcher.yml

  - name: install flatpak
    import_tasks: install-flatpak.yml

  - name: install yq
    import_tasks: install-yq.yml

  - name: install xorg
    become: yes
    import_tasks: xorg.yml

  - name: install oh-my-zsh
    import_tasks: install-oh-my-zsh.yml



  - name: install rust
    vars:
      rust_user: "{{ user }}"
    block:
      - import_tasks: install-rustup.yml
      - import_tasks: install-rust-analyzer.yml

#  - import_tasks: install-rustdesk.yml

  - import_tasks: install-bluetooth.yml

  - import_tasks: install-appimages.yml

#  - import_tasks: install-borgbackup.yml

  - name: install go
    vars:
      go_user: "{{ user }}"
    block:
      - import_tasks: install-go.yml
      - import_tasks: install-gopls.yml


  - name: install asdf
    vars:
      asdf_user: "{{ user }}"
      asdf_dir: "/home/{{ asdf_user }}/.asdf"
      asdf_cfg: "{{ asdf_dif }}/.asdfrc"
    block:
      - import_tasks: install-asdf.yml

  - name: install abcde
    import_tasks: install-abcde.yml

  - name: install ansible lsp
    import_tasks: install-ansible-lsp.yml

  - name: install helix
    import_tasks: install-helix.yml

  - name: install neovim
    import_tasks: install-neovim.yml


  - name: install keepassx
    import_tasks: install-keepassxc.yml

  - name: install jupyter notebook
    import_tasks: install-jupyter-notebook.yml

  - name: install ignite
    import_tasks: install-ignite.yml