  - name: config xmonad
    when: ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]
    block:
    - name: "create {{ xmonad_config_dir }}/lib"
      file:
        path: "{{ xmonad_config_dir }}/lib"
        state: directory
    - name: "link ~/{{ xmonad_config_dir }}/xmonad.hs from dotfiles"
      file:
        src: "{{ dot_files }}/home/.xmonad/xmonad.hs"
        dest: "{{ xmonad_config_dir }}/xmonad.hs"
        state: link
    - name: "link ~/{{ xmonad_config_dir }}/build from dotfiles"
      file:
        src: "{{ dot_files }}/home/.xmonad/build"
        dest: "{{ xmonad_config_dir }}/build"
        state: link
    - name: link keyboard layout script
      file:
        src: "{{ dot_files }}/home/.xmonad/switch-kb-layout.sh"
        dest: "{{ xmonad_config_dir }}/switch-kb-layout.sh"
        state: link
    - name: link MyUtils.hs
      file:
        src: "{{ dot_files }}/home/.xmonad/lib/MyUtils.hs"
        dest: "{{ xmonad_config_dir }}/lib/MyUtils.hs"
        state: link

