- name: config oh-my-zsh
  block:
  - name: link .p10k.zsh
    when: ansible_distribution in ['Arch', 'Archlinux', 'Ubuntu']
    file:
      src: "{{ dot_files }}/home/.p10k.zsh"
      dest: "{{ userhome }}/.p10k.zsh"
      state: link
