  - name: config xmonad
    when: ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]
    block:
    - name: "create {{ xmonad_config_dir }}/lib"
      file:
        path: " {{ xmonad_config_dir }}/lib"
        state: directory
    - name: link ~/.xmonad/xmonad.hs from dotfiles
      file:
        src: "{{ dot_files }}/home/.xmonad/xmonad.hs"
        dest: "{{ xmonad_config_dir }}/xmonad.hs"
        state: link
    - name: change config folder path to XDG_HOME_CONFIG folder (ubuntu)
      when: ansible_distribution in [ 'Ubuntu' ]
      replace:
        path: "{{ userhome }}/.xmonad/xmonad.hs"
        regexp: "\"\\.config/xmonad/"
        replace: "\".xmonad/"
    - name: change config folder path to XDG_HOME_CONFIG folder (arch)
      when: ansible_distribution in [ 'Arch', 'Archlinux' ]
      replace:
        path: "{{ userhome }}/.config/xmonad/xmonad.hs"
        regexp: "\"\\.xmonad/"
        replace: "\".config/xmonad/"
    - name: link keyboard layout script
      file:
        src: "{{ dot_files }}/home/.xmonad/switch-kb-layout.sh"
        dest: "{{ xmonad_config_dir }}/switch-kb-layout.sh"
        state: link
    - name: link MyUtils.hs
      file:
        src: "{{ dot_files }}/home/.xmonad/lib/MyUtils.hs"
        dest: "{{ xmonad_config_dir }}/lib/MyUtils.hs"
        state: link