  - name: config xmonad
    when: ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]
    block:
    - name: "link {{ xmonad_config_dir }}/ from dotfiles"
      file:
        src: "{{ dot_files }}/home/.config/xmonad/`"
        path: "{{ xmonad_config_dir }}"
        state: link

