- name: install terraform
  block:
  - name: install terraform (get_url)
    get_url:
      url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
      checksum: "sha256:https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_SHA256SUMS"
      mode: 0755
      dest: "{{ ansible_env.HOME }}/terraform-{{ terraform_version }}.zip"
    register: terraformversion
  - name: install terraform (unarchive)
    unarchive:
      src: "{{ ansible_env.HOME }}/terraform-{{ terraform_version }}.zip"
      dest: "/usr/local/bin"
      mode: 0755
      owner: root
      group: root
    when: terraformversion.changed
  when: terraform_version is defined

