- name: install golang
  block:
  
  - name: install golang (get_url)
    get_url:
      url: https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz
      checksum: "sha256:{{ golang_sha256 }}"
      mode: 0755
      dest: "{{ ansible_env.HOME }}/golang-{{ golang_version }}.tar.gz"
    register: golangversion
  - name: install golang (remove old version)
    file:
      path: /usr/local/go
      state: absent
    when: golangversion.changed
  - name: install golang (unarchive)
    unarchive:
      src: "{{ ansible_env.HOME }}/golang-{{ golang_version }}.tar.gz"
      dest: "/usr/local/"
    when: golangversion.changed
  - name: install golang (add to path)
    lineinfile:
      path: "/etc/profile"
      line: "{{ item.line }}"
    loop:
    - { line: "### go-lang ###" }
    - { line: "export PATH=$PATH:/usr/local/go/bin" }
  when: golang_version is defined

