- name: Add ppa (Ubuntu)
  block:
  - name: Add keepass ppa
    apt_repository:
      repo: ppa:phoerious/keepassxc
      state: present
  - name: apt update
    apt:
      update_cache: true
    changed_when: false
  when: ansible_distribution == 'Ubuntu'

- name: install keepassxc 
  become: true
  package:
    name: 
      - "{{ keepass_package_name }}"

