- name: install wireguard
  when: ansible_distribution in [ 'Ubuntu' ]
  become: true
  package:
    update_cache: true
    name:
      - wireguard
      - wireguard-tools

- name: configure wireguard wg0
  vars:
    wg_folder: "~/keys"
    wg_interface: "wg0"
  block:
    - debug: 
        msg: test
