- name: add user group
  become: true
  when: "add_user and ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]"
  group:
    name: "{{ user }}"
    gid: 1000

- name: add ansible group
  become: true
  when: "add_ansible and ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]"
  group:
    name: ansible 
    gid: "{{ ansible_gid | int }}"

- name: add app_builder group
  become: true
  when: "ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]"
  group:
    name: app_builder

- name: add ansible user
  become: true
  when: "add_ansible and ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]"
  user:
    name: "{{ new_ansible_user }}"
    uid: "{{ ansible_gid | int }}"
    comment: Ansible User
    group: ansible
    shell: /bin/bash
    password: "{{ lookup('ansible.builtin.env','TOOR_PW_HASH', default='!') }}!"
    generate_ssh_key: true
    ssh_key_file: ".ssh/id_ed25519"
    ssh_key_comment: "toor@{{ ansible_hostname }}"
    ssh_key_type: "ed25519"


- name: add user
  become: true
  when: "user_pw_set and ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]"
  user:
    name: "{{ user }}"
    comment: Lars
    uid: 1000
    group: "{{ user }}"
    password: "{{ lookup('ansible.builtin.env','USER_PW_HASH') }}"
    generate_ssh_key: true
    ssh_key_file: ".ssh/id_ed25519"
    ssh_key_comment: "{{ user }}@{{ ansible_hostname }}"
    ssh_key_type: "ed25519"
    # FIXME some systems use %sudo instead of %wheel for sudo group
    groups:
      - 'wheel'

- name: Create the `app_builder` user
  when: ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]
  ansible.builtin.user:
    name: app_builder
    create_home: yes
    group: app_builder
    shell: /bin/bash

- name: update /etc/sudoers
  block:
    - name: enable wheel
      replace:
        path: /etc/sudoers
        regexp: "^# (%wheel ALL=\\(ALL:ALL\\) ALL)$"
        replace: "\\1"
        validate: 'visudo -cf %s'
    - name: enable no pw for group ansible
      lineinfile:
        path: "/etc/sudoers.d/01_ansible"
        line: "%ansible ALL=(ALL:ALL) NOPASSWD: ALL"
        create: yes
        mode: 0644
        validate: 'visudo -cf %s'
    - name: Allow the `app_builder` user to run `sudo pacman` without a password
      when: ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]
      lineinfile:
        path: /etc/sudoers.d/11-install-app_builder
        line: 'app_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        mode: 0644
        validate: 'visudo -cf %s'

