- name: enable multilib repo (Arch)
  when: ansible_distribution in [ 'Archlinux' ]
  replace:
    dest: /etc/pacman.conf
    regexp: "#(\\s*\\[multilib\\]\\s*\n#\\s*Include\\s+=\\s+/etc/pacman.d/mirrorlist)"
    backup: yes
    replace: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
- name: add base packages
  when: ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]
  vars:
    distro_packages:
      'Arch':
        networkmanager: 'networkmanager'
      'Archlinux':
        networkmanager: 'networkmanager'
      'Ubuntu':
        networkmanager: 'network-manager'
  package:
    name:
      - sudo
      - "{{ distro_packages[ansible_distribution]['networkmanager'] | default ('') }}"  # network manager
      - tmux
      - vim
      - zip
      - unzip
      - rsync
      - man

- name: add sshd packages
  when: ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]
  package:
    name:
      - openssh
      - sshpass
  tags: [ 'never','sshd' ]


- name: enable NetworkManager.service
  when: ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]
  systemd:
    name: NetworkManager.service
    state: started
    enabled: true

- name: enable sshd.service
  when: ansible_distribution in [ 'Ubuntu', 'Arch', 'Archlinux' ]
  systemd:
    name: sshd.service
    state: started
    enabled: true
  tags: [ 'never','sshd' ]

- name: alias vim as vi via softlink
  when: ansible_distribution in [ 'Arch', 'Archlinux' ]
  file:
    src: /usr/bin/vim
    dest: /usr/bin/vi
    state: link
