- name: add base packages
  package:
    name:
      - openssh
      - sshpass
      - sudo
      - networkmanager
      - tmux
      - vim
      - zip
      - unzip
- name: update /etc/sudoers
  block:
    - name: enable wheel
      replace:
        path: /etc/sudoers
        regexp: "^# (%wheel ALL=\\(ALL:ALL\\) ALL)$"
        replace: "\\1"
    - name: enable no pw for group ansible
      lineinfile:
        path: "/etc/sudoers.d/01_ansible"
        line: "%ansible ALL=(ALL:ALL) NOPASSWD: ALL"

- name: enable NetworkManager.service
  systemd:
    name: NetworkManager.service
    state: started
    enabled: true

- name: enable sshd.service
  systemd:
    name: sshd.service
    state: started
    enabled: true


- name: alias vim as vi via softlink
  file:
    src: /usr/bin/vim
    dest: /usr/bin/vi
    state: link
