- name: clone {{ dot_files_repo }}
  become: true
  become_user: "{{ user }}"
  when: add_user
  vars:
  ansible.builtin.git:
    repo: "{{ dot_files_repo }}"
    dest: "{{ user_home }}/dotfiles"
    accept_hostkey: true
