- vars:
    add_user: "{{ lookup('ansible.builtin.env','USER_NM') | length>0 }}"
    user: "{{ lookup('env','USER_NM') }}"
    user_pw_set: "{{ lookup('ansible.builtin.env','USER_PW_HASH')|length>0 }}"
    user_home: "/home/{{ lookup('env','USER_NM') }}"
    add_ansible: "{{ lookup('ansible.builtin.env','TOOR_UID') | length>0 }}"
    ansible_pw_set: "{{ lookup('ansible.builtin.env','TOOR_PW_HASH')|length>0 }}"
    ansible_gid: "{{ lookup('ansible.builtin.env','TOOR_UID', default='1001') | int }}"
  block:
  - name: query
    debug:
      var: ansible_facts
    tags: [ 'never', 'debug' ]
  - name: install base packages
    import_tasks: add-base-packages.yml
  - name: add user
    import_tasks: add-user.yml
  - name: install paru
    import_tasks: install-paru.yml

